### ISSUE TITLE
setstakesplitthreshold not functioning correctly

### ISSUE THREAD

**Issue by meatfish2020** [bulwark-crypto/Bulwark#134]
**Describe the bug**
I used bulwark-cli setstakesplitthreshold to set a threshold of 101 but certain inputs (not all) are splitting so that one piece is lower than 101. No splits are equal halves. As far as I can determine it is splitting so that at least one of the resulting inputs is higher than 101, but not both.

**To Reproduce**
via command line on Ubuntu 16.04:
$ bulwark-cli setstakesplitthreshold 101
Wait for stakes.
Stakes are unequal.
Some splits, perhaps coincidently all those around the 180 BWK level, split to just over 100 on one input and 80-something on the other. Those at levels lower (e.g. 130BWK) don't split.

**Expected behavior**
Inputs are divided into two equal parts after each stake as long as each input will remain >101.

**Transactions**
See example txid for bug: 
cfadc36f92bea87933175b03480df09f4265b273aae40a88860bd8bb0b113210

See this example for no split with lower input:
23cc1cea5b4c3c097247f8fa7e68d8e757f0b218d802444d1982f9e8a32a9f97

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
- Vultr VPS

**Comment by dustinengle** [comment]
https://github.com/bulwark-crypto/Bulwark/blob/master/src/wallet.cpp#L2658
Currently, the wallet will only split the stake at the threshold a single time.

Example scenario:
The stake split threshold will only split the stake amount if it is greater than the threshold.  The system does not currently split into equal amounts, it splits so that 1 piece is below the threshold.

The split threshold:
`setstakesplitthreshold = 2000 BWK (default)`

The amount being staked:
`stake amount = 6000 BWK`

After the stake the split amounts will be:
`2000 BWK` the threshold split
`4000 BWK + reward` the remaining amount after the split

An ideal split would be:
`2000 BWK`
`2000 BWK`
`2000 BWK`
`stake reward BWK`
