### ISSUE TITLE
bulwarkd.

### ISSUE THREAD

**Issue by bobozm** [bulwark-crypto/Bulwark#26]
how would I be able to run two daemon on one machine incase one timesout/fails out of sync

**Comment by kewagi** [comment]
Do you actually want to run two daemons at the same time, or are you talking about a "backup daemon" that turns on when the other fails?

**Comment by bobozm** [comment]
Backup

**Comment by kewagi** [comment]
It depends on your operating system, on modern versions of Ubuntu for example, you'd want to create a system service for bulwarkd and tell it to always restart on crash via the `Restart=always` parameter. 

If you need help, this is better discussed in our Discord chat since this is not an issue with Bulwark.
